//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praksa
{
    using System;
    using System.Collections.Generic;
    
    public partial class MK_PROTECTEDAREAS_EEACDDAV15__ATTACH
    {
        public int ATTACHMENTID { get; set; }
        public int REL_OBJECTID { get; set; }
        public string CONTENT_TYPE { get; set; }
        public string ATT_NAME { get; set; }
        public int DATA_SIZE { get; set; }
        public byte[] DATA { get; set; }
    }
}
