//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praksa
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MK_PROTECTEDAREAS_EEACDDAV15
    {
        public int OBJECTID { get; set; }
        [Display(Name="Site Code")]
        public Nullable<int> SITE_CODE { get; set; }
        public string PARENT_ISO { get; set; }
        public string ISO3 { get; set; }
        [Display(Name = "Site Name")]
        public string SITE_NAME { get; set; }
        [Display(Name = "Site Area")]
        public Nullable<decimal> SITE_AREA { get; set; }

        [Display(Name = "Year")]
        public Nullable<int> YEAR { get; set; }
        public string DESIG_ABBR { get; set; }
        public string DESIGNATE { get; set; }
        public string ODESIGNATE { get; set; }
        public string IUCNCAT { get; set; }
        public string CDDA_disse { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }

        [Display(Name = "Municipality")]
        public string MUNICIPALITY { get; set; }
    }
}
