//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praksa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GISTelerikEntities : DbContext
    {
        public GISTelerikEntities()
            : base("name=GISTelerikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MK_PROTECTEDAREAS_EEACDDAV15> MK_PROTECTEDAREAS_EEACDDAV15 { get; set; }
        public virtual DbSet<MK_PROTECTEDAREAS_EEACDDAV15__ATTACH> MK_PROTECTEDAREAS_EEACDDAV15__ATTACH { get; set; }
    }
}
